version: '3.8'

services:
  api:
    image: auroraphtgrp/uniko-finance-bot:latest
    container_name: uniko-finance-bot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python api.py
    restart: unless-stopped

networks:
  uniko-network:
    driver: bridge
