version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: uniko-finance-bot
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - uniko-network

networks:
  uniko-network:
    driver: bridge
